/**
 * Agent execution events (port of `pyagentspec.tracing.events.agent`).
 */
import type { Agent } from "../../agents/index.js";
import { Event, type EventOptions } from "./event.js";

export interface AgentExecutionStartOptions extends EventOptions {
  /** The Agent being executed */
  agent: Agent;
  /** The inputs used for the agent's execution, one per property defined in agent's inputs (sensitive) */
  inputs: Record<string, unknown>;
}

/** The execution of an agent is starting. Emitted when an AgentExecutionSpan starts. */
export class AgentExecutionStart extends Event {
  agent: Agent;
  inputs: Record<string, unknown>;

  override get type(): string {
    return "AgentExecutionStart";
  }

  constructor(options: AgentExecutionStartOptions) {
    super(options);
    this.agent = options.agent;
    this.inputs = options.inputs;
  }
}

export interface AgentExecutionEndOptions extends EventOptions {
  /** The Agent being executed */
  agent: Agent;
  /** The outputs generated by the agent's execution, one per property defined in agent's outputs (sensitive) */
  outputs: Record<string, unknown>;
}

/** The execution of an agent is ending. Emitted when an AgentExecutionSpan ends. */
export class AgentExecutionEnd extends Event {
  agent: Agent;
  outputs: Record<string, unknown>;

  override get type(): string {
    return "AgentExecutionEnd";
  }

  constructor(options: AgentExecutionEndOptions) {
    super(options);
    this.agent = options.agent;
    this.outputs = options.outputs;
  }
}
