/**
 * Flow execution events (port of `pyagentspec.tracing.events.flow`).
 */
import type { Flow } from "../../flows/index.js";
import { Event, type EventOptions } from "./event.js";

export interface FlowExecutionStartOptions extends EventOptions {
  /** The Flow being executed */
  flow: Flow;
  /** The inputs used for the flow's execution, one per property defined in flow's inputs (sensitive) */
  inputs: Record<string, unknown>;
}

/** The execution of a flow is starting. Emitted when a FlowExecutionSpan starts. */
export class FlowExecutionStart extends Event {
  flow: Flow;
  inputs: Record<string, unknown>;

  override get type(): string {
    return "FlowExecutionStart";
  }

  constructor(options: FlowExecutionStartOptions) {
    super(options);
    this.flow = options.flow;
    this.inputs = options.inputs;
  }
}

export interface FlowExecutionEndOptions extends EventOptions {
  /** The Flow being executed */
  flow: Flow;
  /** The outputs generated by the flow's execution, one per property defined in flow's outputs (sensitive) */
  outputs: Record<string, unknown>;
  /** The exit branch selected at the end of the Flow's execution */
  branchSelected: string;
}

/** The execution of a flow is ending. Emitted when a FlowExecutionSpan ends. */
export class FlowExecutionEnd extends Event {
  flow: Flow;
  outputs: Record<string, unknown>;
  branchSelected: string;

  override get type(): string {
    return "FlowExecutionEnd";
  }

  constructor(options: FlowExecutionEndOptions) {
    super(options);
    this.flow = options.flow;
    this.outputs = options.outputs;
    this.branchSelected = options.branchSelected;
  }
}
