/**
 * ManagerWorkers execution events (port of `pyagentspec.tracing.events.managerworkers`).
 */
import type { ManagerWorkers } from "../../agents/index.js";
import { Event, type EventOptions } from "./event.js";

export interface ManagerWorkersExecutionStartOptions extends EventOptions {
  /** The ManagerWorkers being executed */
  managerworkers: ManagerWorkers;
  /** The inputs used for the manager-workers's execution, one per property defined in manager-workers's inputs (sensitive) */
  inputs: Record<string, unknown>;
}

/** The execution of a manager-workers is starting. Emitted when a ManagerWorkersExecutionSpan starts. */
export class ManagerWorkersExecutionStart extends Event {
  managerworkers: ManagerWorkers;
  inputs: Record<string, unknown>;

  override get type(): string {
    return "ManagerWorkersExecutionStart";
  }

  constructor(options: ManagerWorkersExecutionStartOptions) {
    super(options);
    this.managerworkers = options.managerworkers;
    this.inputs = options.inputs;
  }
}

export interface ManagerWorkersExecutionEndOptions extends EventOptions {
  /** The ManagerWorkers being executed */
  managerworkers: ManagerWorkers;
  /** The outputs generated by the manager-workers's execution, one per property defined in manager-workers's outputs (sensitive) */
  outputs: Record<string, unknown>;
}

/** The execution of a manager-workers is ending. Emitted when a ManagerWorkersExecutionSpan ends. */
export class ManagerWorkersExecutionEnd extends Event {
  managerworkers: ManagerWorkers;
  outputs: Record<string, unknown>;

  override get type(): string {
    return "ManagerWorkersExecutionEnd";
  }

  constructor(options: ManagerWorkersExecutionEndOptions) {
    super(options);
    this.managerworkers = options.managerworkers;
    this.outputs = options.outputs;
  }
}
