/**
 * Node execution events (port of `pyagentspec.tracing.events.node`).
 */
import type { Node } from "../../flows/index.js";
import { Event, type EventOptions } from "./event.js";

export interface NodeExecutionStartOptions extends EventOptions {
  /** The Node being executed */
  node: Node;
  /** The inputs used for the node's execution, one per property defined in node's inputs (sensitive) */
  inputs: Record<string, unknown>;
}

/** The execution of a node is starting. Emitted when a NodeExecutionSpan starts. */
export class NodeExecutionStart extends Event {
  node: Node;
  inputs: Record<string, unknown>;

  override get type(): string {
    return "NodeExecutionStart";
  }

  constructor(options: NodeExecutionStartOptions) {
    super(options);
    this.node = options.node;
    this.inputs = options.inputs;
  }
}

export interface NodeExecutionEndOptions extends EventOptions {
  /** The Node being executed */
  node: Node;
  /** The outputs generated by the node's execution, one per property defined in node's outputs (sensitive) */
  outputs: Record<string, unknown>;
  /** The exit branch selected at the end of the Node's execution */
  branchSelected: string;
}

/** The execution of a node is ending. Emitted when a NodeExecutionSpan ends. */
export class NodeExecutionEnd extends Event {
  node: Node;
  outputs: Record<string, unknown>;
  branchSelected: string;

  override get type(): string {
    return "NodeExecutionEnd";
  }

  constructor(options: NodeExecutionEndOptions) {
    super(options);
    this.node = options.node;
    this.outputs = options.outputs;
    this.branchSelected = options.branchSelected;
  }
}
