/**
 * Swarm execution events (port of `pyagentspec.tracing.events.swarm`).
 */
import type { Swarm } from "../../agents/index.js";
import { Event, type EventOptions } from "./event.js";

export interface SwarmExecutionStartOptions extends EventOptions {
  /** The Swarm being executed */
  swarm: Swarm;
  /** The inputs used for the swarm's execution, one per property defined in swarm's inputs (sensitive) */
  inputs: Record<string, unknown>;
}

/** The execution of a swarm is starting. Emitted when a SwarmExecutionSpan starts. */
export class SwarmExecutionStart extends Event {
  swarm: Swarm;
  inputs: Record<string, unknown>;

  override get type(): string {
    return "SwarmExecutionStart";
  }

  constructor(options: SwarmExecutionStartOptions) {
    super(options);
    this.swarm = options.swarm;
    this.inputs = options.inputs;
  }
}

export interface SwarmExecutionEndOptions extends EventOptions {
  /** The Swarm being executed */
  swarm: Swarm;
  /** The outputs generated by the swarm's execution, one per property defined in swarm's outputs (sensitive) */
  outputs: Record<string, unknown>;
}

/** The execution of a swarm is ending. Emitted when a SwarmExecutionSpan ends. */
export class SwarmExecutionEnd extends Event {
  swarm: Swarm;
  outputs: Record<string, unknown>;

  override get type(): string {
    return "SwarmExecutionEnd";
  }

  constructor(options: SwarmExecutionEndOptions) {
    super(options);
    this.swarm = options.swarm;
    this.outputs = options.outputs;
  }
}
