/**
 * Tool execution events (port of `pyagentspec.tracing.events.tool`).
 */
import type { Tool } from "../../tools/index.js";
import { Event, type EventOptions } from "./event.js";

export interface ToolExecutionRequestOptions extends EventOptions {
  /** The Tool being executed */
  tool: Tool;
  /** The input values that should be used to execute the tool, one per property defined in tool's inputs (sensitive) */
  inputs: Record<string, unknown>;
  /** Identifier of the tool execution request */
  requestId: string;
}

/** A tool execution request is received. Emitted when a ToolExecutionSpan starts, or a client tool is called. */
export class ToolExecutionRequest extends Event {
  tool: Tool;
  inputs: Record<string, unknown>;
  requestId: string;

  override get type(): string {
    return "ToolExecutionRequest";
  }

  constructor(options: ToolExecutionRequestOptions) {
    super(options);
    this.tool = options.tool;
    this.inputs = options.inputs;
    this.requestId = options.requestId;
  }
}

export interface ToolExecutionResponseOptions extends EventOptions {
  /** The Tool being executed */
  tool: Tool;
  /** The return value generated by the tool's execution, one per property defined in tool's outputs (sensitive) */
  outputs: Record<string, unknown>;
  /** Identifier of the tool execution request */
  requestId: string;
}

/** A tool execution finishes and a result is received. Raised when a ToolExecutionSpan ends, or a client tool result is received. */
export class ToolExecutionResponse extends Event {
  tool: Tool;
  outputs: Record<string, unknown>;
  requestId: string;

  override get type(): string {
    return "ToolExecutionResponse";
  }

  constructor(options: ToolExecutionResponseOptions) {
    super(options);
    this.tool = options.tool;
    this.outputs = options.outputs;
    this.requestId = options.requestId;
  }
}

export interface ToolConfirmationRequestOptions extends EventOptions {
  /** The Tool being executed */
  tool: Tool;
  /** Identifier of the confirmation request */
  requestId: string;
  /** Identifier of the tool execution request this confirmation relates to */
  toolExecutionRequestId?: string | null;
}

/** A tool confirmation request is raised. */
export class ToolConfirmationRequest extends Event {
  tool: Tool;
  requestId: string;
  toolExecutionRequestId: string | null;

  override get type(): string {
    return "ToolConfirmationRequest";
  }

  constructor(options: ToolConfirmationRequestOptions) {
    super(options);
    this.tool = options.tool;
    this.requestId = options.requestId;
    this.toolExecutionRequestId = options.toolExecutionRequestId ?? null;
  }
}

export interface ToolConfirmationResponseOptions extends EventOptions {
  /** The Tool being executed */
  tool: Tool;
  /** Whether the execution of the tool was confirmed */
  executionConfirmed: boolean;
  /** Identifier of the confirmation request */
  requestId: string;
  /** Identifier of the tool execution request this confirmation relates to */
  toolExecutionRequestId?: string | null;
}

/** A tool confirmation response is received. */
export class ToolConfirmationResponse extends Event {
  tool: Tool;
  executionConfirmed: boolean;
  requestId: string;
  toolExecutionRequestId: string | null;

  override get type(): string {
    return "ToolConfirmationResponse";
  }

  constructor(options: ToolConfirmationResponseOptions) {
    super(options);
    this.tool = options.tool;
    this.executionConfirmed = options.executionConfirmed;
    this.requestId = options.requestId;
    this.toolExecutionRequestId = options.toolExecutionRequestId ?? null;
  }
}

export interface ToolExecutionStreamingChunkReceivedOptions extends EventOptions {
  /** The Tool being executed */
  tool: Tool;
  /** Identifier of the tool execution request */
  requestId: string;
  /** A streamed portion of the tool's output emitted during execution (sensitive) */
  content: string;
}

/** A tool streams a portion of the output during its execution. */
export class ToolExecutionStreamingChunkReceived extends Event {
  tool: Tool;
  requestId: string;
  content: string;

  override get type(): string {
    return "ToolExecutionStreamingChunkReceived";
  }

  constructor(options: ToolExecutionStreamingChunkReceivedOptions) {
    super(options);
    this.tool = options.tool;
    this.requestId = options.requestId;
    this.content = options.content;
  }
}
