/**
 * Agent Spec Flow -> LangGraph StateGraph compilation.
 *
 * Port of the Flow section of
 * `pyagentspec.adapters.langgraph._langgraphconverter`: one graph node per
 * flow node (named by the AgentSpec node id), conditional edges routed on the
 * last executed branch, MapNode iteration wiring and data-flow edge
 * auto-generation. Node executors are built by the converter through the
 * `convertNode` callback, keeping the recursive (memoized) component
 * conversion out of this module.
 *
 * Runtime contracts (state keys, node names, error-message text) mirror the
 * Python adapter exactly so specs behave the same across both SDKs.
 */
import type { BaseMessage } from "@langchain/core/messages";
import type { RunnableConfig } from "@langchain/core/runnables";
import type { BaseCheckpointSaver } from "@langchain/langgraph";
import { Annotation, START, StateGraph } from "@langchain/langgraph";
import type { ComponentWithIO } from "../../component.js";
import type {
  ControlFlowEdge,
  DataFlowEdge,
  Flow,
  MapNode,
  Node,
} from "../../flows/index.js";
import { DEFAULT_NEXT_BRANCH, createDataFlowEdge } from "../../flows/index.js";
import type { Property } from "../../property.js";
import { jsonSchemasHaveSameType } from "../common/index.js";
import type { NodeExecutor } from "./node-execution.js";
import { EndNodeExecutor, MapNodeExecutor } from "./node-execution.js";
import { patchWithExecutionSpan } from "./tracing.js";
import type {
  DynamicStateGraph,
  FlowState,
  NextNodeInputs,
  NodeExecutionDetails,
  NodeOutputs,
} from "./types.js";

/** Options for `compileFlow`. */
export interface CompileFlowOptions {
  /**
   * Builds the node executor for one flow node. Provided by the converter
   * (recursive conversion, memoized by component id).
   */
  convertNode: (node: Node) => Promise<NodeExecutor>;
  /** Checkpointer wired into the compiled graph. */
  checkpointer?: BaseCheckpointSaver;
}

/** A last-value channel with an initial default. */
function lastValueChannel<T>(defaultValue: () => T) {
  return Annotation<T>({
    reducer: (_current: T, update: T) => update,
    default: defaultValue,
  });
}

function findPropertyByTitle(
  properties: Property[],
  title: string,
  context: string,
): Property {
  const property = properties.find((candidate) => candidate.title === title);
  if (property === undefined) {
    throw new Error(`Property \`${title}\` was not found in ${context}.`);
  }
  return property;
}

/**
 * Select which of a MapNode's inputs it should iterate over, based on the
 * type of the outputs they are connected to: a declared data-flow edge whose
 * source output is an array of the matching subflow input type iterates.
 * Mirroring Python, only explicitly declared data-flow connections take part.
 */
function selectMapNodeIteratedInputs(flow: Flow, node: MapNode): string[] {
  const inputsToIterate: string[] = [];
  for (const dataFlowEdge of flow.dataFlowConnections ?? []) {
    if (String(dataFlowEdge.destinationNode["id"]) !== node.id) {
      continue;
    }
    const sourceProperty = findPropertyByTitle(
      (dataFlowEdge.sourceNode["outputs"] as Property[] | undefined) ?? [],
      dataFlowEdge.sourceOutput,
      `the outputs of node \`${String(dataFlowEdge.sourceNode["name"])}\``,
    );
    const innerFlowInputProperty = findPropertyByTitle(
      (node.subflow["inputs"] as Property[] | undefined) ?? [],
      dataFlowEdge.destinationInput.replace("iterated_", ""),
      `the inputs of the subflow of MapNode \`${node.name}\``,
    );
    // Compare against an array-of-inner-input schema, like Python's
    // ListProperty(item_type=inner).json_schema (titles are ignored by
    // the comparison).
    if (
      jsonSchemasHaveSameType(sourceProperty.jsonSchema, {
        type: "array",
        items: innerFlowInputProperty.jsonSchema,
      })
    ) {
      inputsToIterate.push(dataFlowEdge.destinationInput);
    }
  }
  return inputsToIterate;
}

/**
 * Manually create data flow connections when they are not given in the flow:
 * one edge per matching-title (source output, destination input) pair. This
 * is the conversion recommended by the Agent Spec language specification.
 */
function autoGenerateDataFlowEdges(flowNodes: Node[]): DataFlowEdge[] {
  const dataFlowConnections: DataFlowEdge[] = [];
  for (const sourceNode of flowNodes) {
    for (const destinationNode of flowNodes) {
      for (const sourceOutput of sourceNode.outputs ?? []) {
        for (const destinationInput of destinationNode.inputs ?? []) {
          if (sourceOutput.title === destinationInput.title) {
            dataFlowConnections.push(
              createDataFlowEdge({
                name: `${sourceNode.name}-${destinationNode.name}-${sourceOutput.title}`,
                sourceNode: sourceNode as unknown as ComponentWithIO,
                sourceOutput: sourceOutput.title,
                destinationNode: destinationNode as unknown as ComponentWithIO,
                destinationInput: destinationInput.title,
              }),
            );
          }
        }
      }
    }
  }
  return dataFlowConnections;
}

/** Add one conditional edge per source node, routing on the last branch. */
function addConditionalEdgesToGraph(
  controlFlowConnections: ControlFlowEdge[],
  graphBuilder: DynamicStateGraph,
): void {
  const controlFlow = new Map<string, Record<string, string>>();
  for (const controlFlowEdge of controlFlowConnections) {
    const sourceNodeId = String(controlFlowEdge.fromNode["id"]);
    let mapping = controlFlow.get(sourceNodeId);
    if (mapping === undefined) {
      mapping = {};
      controlFlow.set(sourceNodeId, mapping);
    }
    // Python's `from_branch or DEFAULT_NEXT_BRANCH`: an empty-string
    // branch coerces to the default branch too, not just null/undefined.
    const branchName = controlFlowEdge.fromBranch || DEFAULT_NEXT_BRANCH;
    mapping[branchName] = String(controlFlowEdge.toNode["id"]);
  }
  for (const [sourceNodeId, controlFlowMapping] of controlFlow) {
    graphBuilder.addConditionalEdges(
      sourceNodeId,
      (state: FlowState) =>
        state.node_execution_details?.branch ?? DEFAULT_NEXT_BRANCH,
      controlFlowMapping,
    );
  }
}

/**
 * Compile an Agent Spec Flow into a LangGraph StateGraph wrapped in the flow
 * execution span.
 */
export async function compileFlow(
  flow: Flow,
  options: CompileFlowOptions,
): Promise<unknown> {
  // The input/output schemas must reference the SAME channel instances as
  // the state schema, or StateGraph rejects them as conflicting channels.
  const inputsChannel = lastValueChannel<NextNodeInputs>(() => ({}));
  const outputsChannel = lastValueChannel<NodeOutputs>(() => ({}));
  const messagesChannel = lastValueChannel<BaseMessage[]>(() => []);
  const nodeExecutionDetailsChannel = lastValueChannel<NodeExecutionDetails>(
    () => ({}),
  );
  const graphBuilder = new StateGraph({
    state: Annotation.Root({
      inputs: inputsChannel,
      outputs: outputsChannel,
      messages: messagesChannel,
      node_execution_details: nodeExecutionDetailsChannel,
    }),
    input: Annotation.Root({
      inputs: inputsChannel,
      messages: messagesChannel,
    }),
    output: Annotation.Root({
      outputs: outputsChannel,
      messages: messagesChannel,
      node_execution_details: nodeExecutionDetailsChannel,
    }),
  }) as unknown as DynamicStateGraph;

  graphBuilder.addEdge(START, String(flow.startNode["id"]));

  const flowNodes = flow.nodes as unknown as Node[];
  const nodeExecutors = new Map<string, NodeExecutor>();
  for (const node of flowNodes) {
    nodeExecutors.set(node.id, await options.convertNode(node));
  }

  // Tell the MapNodes which inputs they should iterate over; give EndNodes
  // the flow outputs to reshape their result.
  for (const node of flowNodes) {
    if (node.componentType === "MapNode") {
      const nodeExecutor = nodeExecutors.get(node.id);
      if (nodeExecutor instanceof MapNodeExecutor) {
        nodeExecutor.setInputsToIterate(
          selectMapNodeIteratedInputs(flow, node),
        );
      }
    } else if (node.componentType === "EndNode") {
      const nodeExecutor = nodeExecutors.get(node.id);
      if (nodeExecutor instanceof EndNodeExecutor) {
        nodeExecutor.setFlowOutputs(flow.outputs ?? []);
      }
    }
  }

  for (const [nodeId, nodeExecutor] of nodeExecutors) {
    // Graph node names are the AgentSpec node ids.
    graphBuilder.addNode(nodeId, (state: FlowState, config: RunnableConfig) =>
      nodeExecutor.call(state, config),
    );
  }

  const dataFlowConnections =
    flow.dataFlowConnections === undefined
      ? autoGenerateDataFlowEdges(flowNodes)
      : flow.dataFlowConnections;

  for (const dataFlowEdge of dataFlowConnections) {
    // Flow validation guarantees every edge endpoint is a node of the flow.
    nodeExecutors
      .get(String(dataFlowEdge.sourceNode["id"]))!
      .attachEdge(dataFlowEdge);
  }

  addConditionalEdgesToGraph(flow.controlFlowConnections, graphBuilder);

  const compiledGraph = graphBuilder.compile(
    options.checkpointer !== undefined
      ? { checkpointer: options.checkpointer }
      : {},
  );
  return patchWithExecutionSpan(compiledGraph, {
    kind: "flow",
    component: flow,
  });
}
