# Copyright © 2025 Oracle and/or its affiliates.
#
# This software is under the Apache License 2.0
# (LICENSE-APACHE or http://www.apache.org/licenses/LICENSE-2.0) or Universal Permissive License
# (UPL) 1.0 (LICENSE-UPL or https://oss.oracle.com/licenses/upl), at your option.

from typing import Any, Dict, Optional

from pyagentspec.sensitive_field import SensitiveField
from pyagentspec.tools import Tool
from pyagentspec.tracing.events.event import Event


class ToolExecutionRequest(Event):
    """A tool execution request is received. Emitted when a ToolExecutionSpan starts, or a client tool is called."""

    tool: Tool
    "The Tool being executed"

    inputs: SensitiveField[Dict[str, Any]]
    "The input values that should be used to execute the tool, one per property defined in tool's inputs"

    request_id: str
    "Identifier of the tool execution request"


class ToolExecutionResponse(Event):
    """A tool execution finishes and a result is received. Raised when a ToolExecutionSpan ends, or a client tool result is received."""

    tool: Tool
    "The Tool being executed"

    outputs: SensitiveField[Dict[str, Any]]
    "The return value generated by the tool's execution, one per property defined in tool's outputs"

    request_id: str
    "Identifier of the tool execution request"


class ToolConfirmationRequest(Event):
    """A tool confirmation request is raised."""

    tool: Tool
    "The Tool being executed"

    request_id: str
    "Identifier of the confirmation request"

    tool_execution_request_id: Optional[str] = None
    "Identifier of the tool execution request this confirmation relates to"


class ToolConfirmationResponse(Event):
    """A tool confirmation response is received."""

    tool: Tool
    "The Tool being executed"

    execution_confirmed: bool
    "Whether the execution of the tool was confirmed"

    request_id: str
    "Identifier of the confirmation request"

    tool_execution_request_id: Optional[str] = None
    "Identifier of the tool execution request this confirmation relates to"


class ToolExecutionStreamingChunkReceived(Event):
    """A tool streams a portion of the output during its execution."""

    tool: Tool
    "The Tool being executed"

    request_id: str
    "Identifier of the tool execution request"

    content: SensitiveField[str]
    "A streamed portion of the tool's output emitted during execution"
